stages:
  - test
  - build

# Use Alpine-based Node.js 22 image
image: node:22-alpine

test:
  stage: test
  script:
    - npm ci
    - npm run test

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/ # Adjust this path if your build outputs to a different directory
